<a href="https://colab.research.google.com/github/Anmol9835255787/GeekCamp_FOSS/blob/main/Credit_Card_Fraud_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the Dependencies

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [3]:
credit_card_data = pd.read_csv('/content/creditcard.csv')

In [4]:
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [5]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
7968,10980,1.284388,-0.013181,0.646174,0.198985,-0.568675,-0.526121,-0.448235,-0.167709,1.773223,...,-0.101868,-0.030298,-0.081412,-0.123281,0.278808,1.064001,-0.090181,0.000481,15.95,0.0
7969,10981,1.190428,-0.122329,0.954945,0.267101,-0.971026,-0.652279,-0.612992,-0.003909,1.633117,...,-0.015001,0.127027,0.012079,0.534409,0.112179,1.004483,-0.100188,-0.004774,14.95,0.0
7970,10981,-0.725175,0.298202,1.824761,-2.587170,0.283605,-0.016617,0.153659,0.045084,-0.197611,...,-0.017097,-0.070535,-0.442861,-0.895837,0.624743,-0.510601,-0.031142,0.025564,12.95,0.0
7971,10981,1.226153,-0.129645,0.735197,0.142752,-0.703245,-0.349641,-0.612641,0.020507,1.648986,...,-0.047936,0.040196,-0.057391,-0.012386,0.187685,1.037786,-0.100081,-0.009869,15.95,0.0
7972,10981,1.145381,-0.059349,0.968088,0.267891,-0.822582,-0.597727,-0.450197,-0.119747,1.338188,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7973 entries, 0 to 7972
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    7973 non-null   int64
 1   V1      7973 non-null   float64
 2   V2      7973 non-null   float64
 3   V3      7973 non-null   float64
 4   V4      7973 non-null   float64
 5   V5      7973 non-null   float64
 6   V6      7973 non-null   float64
 7   V7      7973 non-null   float64
 8   V8      7973 non-null   float64
 9   V9      7973 non-null   float64
 10  V10     7973 non-null   float64
 11  V11     7973 non-null   float64
 12  V12     7973 non-null   float64
 13  V13     7973 non-null   float64
 14  V14     7973 non-null   float64
 15  V15     7972 non-null   float64
 16  V16     7972 non-null   float64
 17  V17     7972 non-null   float64
 18  V18     7972 non-null   float64
 19  V19     7972 non-null   float64
 20  V20     7972 non-null   float64
 21  V21     7972 non-null   float64
 22  V22     7972 non-null   float64
 23  V23     7972 non-null   float64
 24  V24     7972 non-null   float64
 25  V25     7972 non-null   float64
 26  V26     7972 non-null   float64
 27  V27     7972 non-null   float64
 28  V28     7972 non-null   float64
 29  Amount  7972 non-null   float64
 30  Class   7972 non-null   float64
dtypes: float64(30), int64(1)
memory usage: 1.9 MB

In [7]:
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [8]:
credit_card_data['Class'].value_counts()

0.0    7947
1.0      25
Name: Class, dtype: int64

This Dataset is highly unblanced

0 --> Normal Transaction

1 --> fraudulent transaction

In [9]:
# separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [10]:
print(legit.shape)
print(fraud.shape)

(7947, 31)
(25, 31)

In [11]:
# statistical measures of the data
legit.Amount.describe()

count    7947.000000
mean       65.284891
std       194.126547
min         0.000000
25%         4.795000
50%        15.950000
75%        54.990000
max      7712.430000
Name: Amount, dtype: float64

In [12]:
fraud.Amount.describe()

count      25.000000
mean      106.308400
std       372.676883
min         0.000000
25%         1.000000
50%         1.000000
75%         1.000000
max      1809.680000
Name: Amount, dtype: float64

In [13]:
# compare the values for both transactions
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,4246.546496,-0.297235,0.286979,0.917142,0.201968,-0.023263,0.164019,-0.019547,-0.072779,0.662196,...,0.042418,-0.055123,-0.165485,-0.034918,0.026636,0.088960,0.019511,0.014875,0.000417,65.284891
1.0,7359.240000,-1.154048,2.930880,-4.757618,4.590240,-0.636103,-1.952536,-2.202403,0.647916,-1.581984,...,0.263011,0.393614,-0.265715,-0.116502,-0.183413,0.067479,0.256994,0.421586,0.237600,106.308400

Under-Sampling

Build a sample dataset containing similar distribution of normal transactions and Fraudulent Transactions

Number of Fraudulent Transactions --> 492

In [14]:
legit_sample = legit.sample(n=492)

Concatenating two DataFrames

In [15]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [16]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
4726,4158,-0.959084,1.504439,1.180137,1.034805,-0.002799,-0.486044,0.384451,-0.207589,1.150690,...,-0.426137,-0.834602,0.085391,-0.085383,-0.398492,0.279005,0.059574,0.255594,11.46,0.0
3179,2754,0.248099,-1.954050,0.501086,0.368722,-1.488571,0.228388,-0.144873,0.080084,0.787018,...,0.210403,-0.348930,-0.426087,0.118882,-0.052273,0.940134,-0.130782,0.088646,500.00,0.0
7152,9371,1.189889,-0.107253,0.704104,0.749776,-0.104521,0.977932,-0.646755,0.234362,1.989812,...,-0.269354,-0.149809,-0.135779,-0.786524,0.515389,0.552193,-0.015602,-0.015397,0.01,0.0
3849,3381,1.275689,1.321378,-2.019144,1.343024,1.647503,-0.737873,0.771878,-0.260791,-0.588714,...,-0.233989,-0.468585,-0.324110,-1.246762,0.968548,-0.205309,0.063859,0.086281,2.31,0.0
4592,3942,-0.598993,0.234646,0.959658,-0.399607,1.681318,-0.985153,0.749743,-0.466928,1.171112,...,-0.110000,0.067873,-0.161011,-0.443499,-0.271569,0.209354,-0.104797,-0.055448,0.00,0.0

In [17]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
6870,8757,-1.863756,3.442644,-4.468260,2.805336,-2.118412,-2.332285,-4.261237,1.701682,-1.439396,...,0.667927,-0.516242,-0.012218,0.070614,0.058504,0.304883,0.418012,0.208858,1.00,1.0
6882,8808,-4.617217,1.695694,-3.114372,4.328199,-1.873257,-0.989908,-4.577265,0.472216,0.472017,...,0.481830,0.146023,0.117039,-0.217565,-0.138776,-0.424453,-1.002041,0.890780,1.10,1.0
6899,8878,-2.661802,5.856393,-7.653616,6.379742,-0.060712,-3.131550,-3.103570,1.778492,-3.831154,...,0.734775,-0.435901,-0.384766,-0.286016,1.007934,0.413196,0.280284,0.303937,1.00,1.0
6903,8886,-2.535852,5.793644,-7.618463,6.395830,-0.065210,-3.136372,-3.104557,1.823233,-3.878658,...,0.716720,-0.448060,-0.402407,-0.288835,1.011752,0.425965,0.413140,0.308205,1.00,1.0
6971,9064,-3.499108,0.258555,-4.489558,4.853894,-6.974522,3.628382,5.431271,-1.946734,-0.775680,...,-1.052368,0.204817,-2.119007,0.170279,-0.393844,0.296367,1.985913,-0.900452,1809.68,1.0

In [18]:
new_dataset['Class'].value_counts()

0.0    492
1.0     25
Name: Class, dtype: int64

In [19]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,4470.180894,-0.187301,0.209206,0.942524,0.169965,-0.040042,0.119145,-0.049924,-0.006513,0.704702,...,0.040452,-0.080611,-0.083505,-0.079172,0.029065,0.087704,-0.004552,0.020771,0.004841,62.33439
1.0,7359.240000,-1.154048,2.930880,-4.757618,4.590240,-0.636103,-1.952536,-2.202403,0.647916,-1.581984,...,0.263011,0.393614,-0.265715,-0.116502,-0.183413,0.067479,0.256994,0.421586,0.237600,106.30840

Splitting the data into Features & Targets

In [20]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [21]:
print(X)

      Time        V1        V2        V3        V4        V5        V6  \
4726  4158 -0.959084  1.504439  1.180137  1.034805 -0.002799 -0.486044
3179  2754  0.248099 -1.954050  0.501086  0.368722 -1.488571  0.228388
7152  9371  1.189889 -0.107253  0.704104  0.749776 -0.104521  0.977932
3849  3381  1.275689  1.321378 -2.019144  1.343024  1.647503 -0.737873
4592  3942 -0.598993  0.234646  0.959658 -0.399607  1.681318 -0.985153
...    ...       ...       ...       ...       ...       ...       ...
6870  8757 -1.863756  3.442644 -4.468260  2.805336 -2.118412 -2.332285
6882  8808 -4.617217  1.695694 -3.114372  4.328199 -1.873257 -0.989908
6899  8878 -2.661802  5.856393 -7.653616  6.379742 -0.060712 -3.131550
6903  8886 -2.535852  5.793644 -7.618463  6.395830 -0.065210 -3.136372
6971  9064 -3.499108  0.258555 -4.489558  4.853894 -6.974522  3.628382

            V7        V8        V9  ...       V20       V21       V22  \
4726  0.384451 -0.207589  1.150690  ...  0.260397 -0.426137 -0.834602
3179 -0.144873  0.080084  0.787018  ...  0.962748  0.210403 -0.348930
7152 -0.646755  0.234362  1.989812  ... -0.146360 -0.269354 -0.149809
3849  0.771878 -0.260791 -0.588714  ...  0.056073 -0.233989 -0.468585
4592  0.749743 -0.466928  1.171112  ...  0.062004 -0.110000  0.067873
...        ...       ...       ...  ...       ...       ...       ...
6870 -4.261237  1.701682 -1.439396  ...  0.360924  0.667927 -0.516242
6882 -4.577265  0.472216  0.472017  ... -0.039046  0.481830  0.146023
6899 -3.103570  1.778492 -3.831154  ...  0.399097  0.734775 -0.435901
6903 -3.104557  1.823233 -3.878658  ...  0.408704  0.716720 -0.448060
6971  5.431271 -1.946734 -0.775680  ... -3.042626 -1.052368  0.204817

           V23       V24       V25       V26       V27       V28   Amount
4726  0.085391 -0.085383 -0.398492  0.279005  0.059574  0.255594    11.46
3179 -0.426087  0.118882 -0.052273  0.940134 -0.130782  0.088646   500.00
7152 -0.135779 -0.786524  0.515389  0.552193 -0.015602 -0.015397     0.01
3849 -0.324110 -1.246762  0.968548 -0.205309  0.063859  0.086281     2.31
4592 -0.161011 -0.443499 -0.271569  0.209354 -0.104797 -0.055448     0.00
...        ...       ...       ...       ...       ...       ...      ...
6870 -0.012218  0.070614  0.058504  0.304883  0.418012  0.208858     1.00
6882  0.117039 -0.217565 -0.138776 -0.424453 -1.002041  0.890780     1.10
6899 -0.384766 -0.286016  1.007934  0.413196  0.280284  0.303937     1.00
6903 -0.402407 -0.288835  1.011752  0.425965  0.413140  0.308205     1.00
6971 -2.119007  0.170279 -0.393844  0.296367  1.985913 -0.900452  1809.68

[517 rows x 30 columns]

In [22]:
print(Y)

4726    0.0
3179    0.0
7152    0.0
3849    0.0
4592    0.0
       ...
6870    1.0
6882    1.0
6899    1.0
6903    1.0
6971    1.0
Name: Class, Length: 517, dtype: float64

Split the data into Training data & Testing Data

In [23]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [ ]:
print(X.shape, X_train.shape, X_test.shape)

(984, 30) (787, 30) (197, 30)

Model Training

Logistic Regression

In [24]:
model = LogisticRegression()

In [25]:
model.fit(X_train, Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

Model Evaluation

Accuracy Score

In [26]:
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [27]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  1.0

In [29]:
# accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [30]:
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.9807692307692307